// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("❌ Missing Supabase configuration");
  console.error("   VITE_SUPABASE_URL:", SUPABASE_URL ? "✅" : "❌");
  console.error("   VITE_SUPABASE_PUBLISHABLE_KEY:", SUPABASE_ANON_KEY ? "✅" : "❌");
  throw new Error("Missing Supabase environment variables");
}

console.log("✅ Supabase initialized successfully");

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => {
        try {
          return localStorage.getItem(key);
        } catch {
          console.warn("⚠️ localStorage.getItem not available");
          return null;
        }
      },
      setItem: (key: string, value: string) => {
        try {
          localStorage.setItem(key, value);
        } catch {
          console.warn("⚠️ localStorage.setItem not available");
        }
      },
      removeItem: (key: string) => {
        try {
          localStorage.removeItem(key);
        } catch {
          console.warn("⚠️ localStorage.removeItem not available");
        }
      },
    },
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});